// How many disticnt terms are in the sequence generated by a^b for 
// 2 <= a <= 100 and 2 <= b <= 100?

#include <iostream>
#include <set>
#include <cmath>

int main(){
  std::set<double> result;
  
  for(int a = 2; a <= 100; ++a)
    for(int b = 2; b <= 100; ++b)
      result.insert(std::pow(a, b));

  std::cout << result.size() << std::endl;
}
